---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-console

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: openshift-console
  labels:
    app: console
    component: ui
spec:
  selector:
    matchLabels:
      app: console
      component: ui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: console
      labels:
        app: console
        component: ui
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
        openshift.io/required-scc: restricted-v2
    spec:
      nodeSelector:
        # node-role.kubernetes.io/master: ""
      restartPolicy: Always
      serviceAccountName: console
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 40
      priorityClassName: system-cluster-critical
      containers:
        - resources:
            requests:
              cpu: 10m
              memory: 100Mi
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - "25"
          name: console
          securityContext:
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          command:
            - /opt/bridge/bin/bridge
            - "--listen=http://0.0.0.0:9000"
            - "--public-dir=/opt/bridge/static"
            - "--branding=okd"
            - "--k8s-mode=off-cluster"
            - "--k8s-mode-off-cluster-endpoint=https://kubernetes.default.svc"
            - "--k8s-mode-off-cluster-skip-verify-tls=true"
            - "--k8s-auth=oidc"
            - "--user-auth=oidc"
            - "--user-auth-oidc-client-id=xxxx"
            - "--user-auth-oidc-issuer-url=https://xxxx.com/"
            - "--user-auth-oidc-client-secret=xxxx"
            - "--user-auth-oidc-client-id=xxxx"
          startupProbe:
            httpGet:
              path: /health
              port: 8443
              scheme: HTTPS
            failureThreshold: 30
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8443
              scheme: HTTPS
            failureThreshold: 1
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8443
              scheme: HTTPS
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: FallbackToLogsOnError
          image: stringang/console:latest-20240923
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 120

---
apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: openshift-console
  labels:
    app: console
  annotations:
    # service.beta.openshift.io/serving-cert-secret-name: console-serving-cert
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  selector:
    app: console
    component: ui
  type: ClusterIP
  sessionAffinity: None