---
apiVersion: audit.k8s.io/v1 # This is required.
kind: Policy
# Don't generate audit events for all requests in RequestReceived stage.
omitStages:
  - "RequestReceived"
  - "ResponseStarted"
rules:
  # The following requests were manually identified as high-volume and low-risk,
  # so drop them.
  - level: None
    users: ["system:kube-proxy"]
    verbs: ["watch"]
    resources:
      - group: "" # core
        resources: ["endpoints", "services"]
  - level: None
    users: ["kubelet"] # legacy kubelet identity
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["nodes"]
  - level: None
    userGroups: ["system:nodes"]
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["nodes"]
  - level: None
    users:
      - system:kube-controller-manager
      - system:kube-scheduler
      - system:serviceaccount:kube-system:endpoint-controller
    verbs: ["get", "update"]
    namespaces: ["kube-system"]
    resources:
      - group: "" # core
        resources: ["endpoints"]
  - level: None
    users: ["system:apiserver"]
    verbs: ["get"]
    resources:
      - group: "" # core
        resources: ["namespaces"]
  # Don't log these read-only URLs.
  - level: None
    nonResourceURLs:
      - /healthz*
      - /version
      - /swagger*
      - /openapi/v2
      - /readyz*
      - /livez*
  # Don't log events requests.
  - level: None
    resources:
      - group: "" # core
        resources: ["events"]
      - group: "events.k8s.io"
        resources: ["events"]
      - group: "authorization.k8s.io"
        resources: ["selfsubjectrulesreviews", "selfsubjectaccessreviews", "subjectaccessreviews"]
      - group: "apps.kruise.io"
        resources: ["status"]
      - group: "authentication.k8s.io"
        resources: ["tokenreviews"]
  - level: None
    resources:
      - group: "apiregistration.k8s.io"
      - group: "coordination.k8s.io"
  # Secrets, ConfigMaps, and TokenReviews can contain sensitive & binary data,
  # so only log at the Metadata level.
  - level: Metadata
    resources:
      - group: "" # core
        resources: ["secrets", "configmaps", "serviceaccounts/token"]
      - group: "authentication.k8s.io"
        resources: ["tokenreviews", "tokenrequests"]
      - group: "certificates.k8s.io"
        resources: ["certificatesigningrequests", "certificatesigningrequests/approval", "certificatesigningrequests/status"]
  # Get repsonses can be large; skip them.

  - level: Request
    verbs: ["create", "update", "delete", "patch"]
    omitManagedFields: true
    resources:
      - group: "networking.k8s.io"
  - level: None
    verbs: ["get", "list", "watch"]
    resources:
      - group: "" # core
      - group: "admissionregistration.k8s.io"
      - group: "apps"
      - group: "authentication.k8s.io"
      - group: "authorization.k8s.io"
      - group: "autoscaling"
      - group: "batch"
      - group: "certificates.k8s.io"
      - group: "extensions"
      - group: "policy"
      - group: "rbac.authorization.k8s.io"
      - group: "settings.k8s.io"
      - group: "storage.k8s.io"
  # Default level for known APIs
  - level: Request
    omitManagedFields: true
    verbs: ["create", "update", "delete", "patch"]
    resources:
      - group: "" # core
      - group: "admissionregistration.k8s.io"
      - group: "apps"
      - group: "authentication.k8s.io"
      - group: "authorization.k8s.io"
      - group: "autoscaling"
      - group: "batch"
      - group: "certificates.k8s.io"
      - group: "extensions"
      - group: "policy"
      - group: "rbac.authorization.k8s.io"
      - group: "settings.k8s.io"
      - group: "storage.k8s.io"
      - group: "autoscaling.alibabacloud.com"
  # Log pvc/pv requests to capture volume details
  - level: Request
    omitManagedFields: true
    verbs: ["create", "delete", "update", "patch"]
    resources:
      - group: ""  # core
        resources: ["persistentvolumeclaims", "persistentvolumes"]
  # Log pod create requests to capture container images, etc.
  - level: Request
    omitManagedFields: true
    verbs: ["create", "update", "delete", "patch"]
    resources:
      - group: ""  # core
        resources: ["pods", "replicacontrollers", "container"]
      - group: "apps"
        resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
      - group: "batch"
        resources: ["jobs", "cronjobs"]
      - group: "extensions" # necessary for pre-1.12 clusters
        resources: ["daemonsets", "deployments", "replicasets"]
      - group: "apps.kruise.io"
        resources: ["clonesets", "statefulsets", "daemonsets"]
  # Log changes to Calico resources
  - level: RequestResponse
    omitManagedFields: true
    verbs: ["create", "update", "delete", "patch"]
    resources:
      - group: "crd.projectcalico.org"
  # Default level for all other requests.
  - level: Metadata
    omitManagedFields: true
    verbs: ["create", "update", "delete", "patch"]