apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.22.15
clusterName: cluster.local
certificatesDir: /etc/kubernetes/ssl
apiServer:
  certSANs:
  - kubernetes
  - kubernetes.default
  - kubernetes.default.svc
  - kubernetes.default.svc.cluster.local
  - localhost
  - 192.168.0.1 # VIP
controlPlaneEndpoint: lb-apiserver.kubernetes.local:6443
controllerManager:
  extraArgs:
    bind-address: 0.0.0.0
    configure-cloud-routes: "false"
    node-cidr-mask-size: "24"
    node-monitor-grace-period: 40s
    node-monitor-period: 5s
    pod-eviction-timeout: 5m0s
    profiling: "False"
    terminated-pod-gc-threshold: "12500"
dns:
  imageRepository: coredns
  imageTag: 1.8.4
etcd:
  local:
    dataDir: /data/etcd
    extraArgs:
      auto-compaction-retention: "8"
      election-timeout: "5000"
      heartbeat-interval: "250"
      metrics: basic
      snapshot-count: "10000"
    imageRepository: google_containers
    imageTag: v3.5.0
    peerCertSANs:
      - etcd.kube-system.svc.cluster.local
      - etcd.kube-system.svc
      - etcd.kube-system
      - etcd
    serverCertSANs:
      - etcd.kube-system.svc.cluster.local
      - etcd.kube-system.svc
      - etcd.kube-system
      - etcd
networking:
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "10.244.0.0/24"
  dnsDomain: "cluster.local"
scheduler:
  extraArgs:
    bind-address: 0.0.0.0