apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # 制定节点调度
      nodeSelector:
        node-role.kubernetes.io/feature: 'true'
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
      # 添加 host
      hostAliases:
        - hostnames:
            - xxxx.com
          ip: 127.0.0.1
      # 调度
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule