---
apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  name: default
spec:
  bpfDataIfacePattern: ^(en.*|eth.*|tunl0$|bond.*)
  bpfEnabled: true # 开启 ebpf 模式
  bpfExternalServiceMode: DSR
  bpfKubeProxyIptablesCleanupEnabled: false
  bpfLogLevel: ''
  logSeverityScreen: Info
  reportingInterval: 0s

---
apiVersion: crd.projectcalico.org/v1
kind: BGPPeer
metadata:
  name: global-peer
spec:
  asNumber: 65177
  peerIP: 10.255.0.1

---
# BGP 模式
apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: default
spec:
  asNumber: 65285
  listenPort: 179
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
  serviceClusterIPs: # 通过 BGP 暴露 service ip ranges
    - cidr: 10.255.16.0/20

---
# 节点 ip ranges 信息
apiVersion: crd.projectcalico.org/v1
kind: BlockAffinity
metadata:
  name: kube-master-192-168-221-64-25
  namespace: ""
spec:
  state: "confirmed"
  node: kube-master
  cidr: 192.168.221.64/25
  deleted: ""

---
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: default-pool
spec:
  allowedUses:
    - Workload
    - Tunnel
  blockSize: 24  #
  cidr: 10.255.128.0/18 # pod subnet
  ipipMode: Never
  natOutgoing: false
  nodeSelector: all()
  vxlanMode: Never